### PR TITLE
Handle keyId in tag

### PR DESCRIPTION
**Pull request by DKvarn**
KeyId can be inside of a tag, it can be tested with example from [Island](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/IS)

### CODE REVIEW

**Comment by dirkx** [comment]
Hmmm - is that valid CBOR ? 

None of the libraries I have here (python, java, javascript and C#) seem to accept this ? And the standard seems to expect an opaque bstring there - no structure with a tag ?

**Comment by DKvarn** [comment]
@dirkx I may have the wrong name (tag) but I need to unwrap the values for the key to get them, have you tested to validate [Island 1.json](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/IS/2DCode/raw/1.json)?

**Comment by dirkx** [comment]
On that one I am seeing:


         [
           / protected / h'a2012604c4483526eba1164a1d54' / {
               \ alg \ 1:-7 \ ECDSA 256 \, 
               \ kid \ 4:4(
                 h'3526eba1164a1d54'
               )
             } / , 
           / unprotected / {}, 
           / payload / h'a401624953041a60a3890b061a609a4e8b390103a101a4617681aa6263696f30312049532f41424331323334234b62636f62495362646e026264746a323032312d30312d303162697378254469726563746f72617465206f66204865616c7468206f66204963656c616e642054657374626d616d4f52472d313030303330323135626d706c45552f312f32302f313532386273640262746769383430353339303036627670674a30374258303363646f626a323030302d30312d3031636e616da462666e6b5072c3b366617261736f6e62676e70c39e6172662041c3b0205072c3b3666163666e746a50524f46415241534f4e63676e746e54484152463c41443c50524f46416376657265312e302e30', 
           / signature / h'f33ba8160454cce0b5bd39fc5c5948e9316b3bbd1a71740e2d7f7d75ffdc9750d632372c0c45c8d2d3311f12a57275da2f8ef6f0edea7276c8d6db652883ad9d'
         ]
       )

I would have expected

       18(
         [
           / protected / h'a20448f3e848e124a38a770126' / {
               \ kid \ 4:h'f3e848e124a38a77', 
               \ alg \ 1:-7 \ ECDSA 256 \
             } / , 
           / unprotected / {}, 
           / payload / h'a4041a618ac061061a609d645101764d696e69737465726f2064656c6c612053616c757465390103a101a4617281a76264756a323032312d31302d333162636f62495462636978263031495437344142313333354143374434393538384234453045454643353634373143332336626973764d696e69737465726f2064656c6c612053616c757465627467693834303533393030366264666a323032312d30352d30346266726a323032312d30352d3032636e616da463666e746944493c43415052494f62666e6944692043617072696f63676e746d4d4152494c553c54455245534162676e6e4d6172696cc3b9205465726573616376657265312e302e3063646f626a313937372d30362d3136', 
           / signature / h'3d75de6ea36136e1feec1fa2c84641a870e2a5a30a2a95bd33c283b193bac37814be08e98b0448b087d15fb5d461e40b836c04e76472fccf382dc15719db4b34'
         ]
       )

(taken from a random other country -- note that the '1' entry is wrong here.

**Comment by DKvarn** [comment]
I agree with you @dirkx , I have seen your question in [testdata #88](https://github.com/eu-digital-green-certificates/dgc-testdata/issues/88) and I think we should put this on hold until your issue are sorted out.

**Comment by dirkx** [comment]
No trouble - the only ones I am tracking are #93 - that is what you mean right ?

**Comment by DKvarn** [comment]
KeyId shouldn't be in a tag

**Pull request closed without merging**
